# Use the official Nginx image as the base image
FROM nginx:latest

# Remove the default Nginx index page
RUN rm -f /usr/share/nginx/html/index.html

# Copy our custom HTML file into the Nginx document root
COPY index.html /usr/share/nginx/html/

# Expose port 80
EXPOSE 80


# FROM python:3.11-slim

# WORKDIR /TASKFLOW

# COPY . .

# RUN npm ci
# RUN npm run build

# EXPOSE 5000

# CMD ["python", "app.py"]
